### ISSUE TITLE
preset messages whatsapp

### ISSUE THREAD

**Issue by marlon33** [canove/whaticket#12]
Hello, i think that's a new enhancement is the system of presets messages, like:
Wellcome, busy, offline, custom msg.

**Comment by esteves67** [comment]
> Hello, i think that's a new enhancement is the system of presets messages, like:
> Wellcome, busy, offline, custom msg.

Already suggested in #4

**Comment by marlon33** [comment]
Oh tks, i hadn't see it before

**Comment by esteves67** [comment]
> Oh tks, i hadn't see it before

Hi @marlon33 
actually, i think im wrong, your suggestion is different than the #4 , so your suggestion is new,
you are talking about Preseted Automatic Messages for when the person is Offline, or Busy, or Offline, 
the #4 is actually about Quick Reply Messages so that you press buttons to send the message so you dont have to type it.

Im sorry! I got it wrong what you said! Sorry about my misinterpretation about what you said!
If you want to re-open the issue, so @canove can label it as enhancement.
