### ISSUE TITLE
error to register

### ISSUE THREAD

**Issue by the-jojo-jj** [canove/whaticket#148]
somebody faces some problem?
please help.

![error](https://user-images.githubusercontent.com/70043720/109786377-ac463c00-7c3f-11eb-941e-ab0e3d7e5120.jpg)

**Comment by crvroberto** [comment]
Hello, Did you start the backend?

**Comment by the-jojo-jj** [comment]
yes, i did. 
do you know how to debug?

**Comment by crvroberto** [comment]
I'm not that good. But I believe that the installation of the back has not been done correctly.

**Comment by the-jojo-jj** [comment]
I'm using debian anyway. 

Somebody know how to run backend in debug mode?

**Comment by esteves67** [comment]
> I'm using debian anyway.
> 
> Somebody know how to run backend in debug mode?

NODE_ENV=DEVELOPMENT      #it helps on debugging
BACKEND_URL=http://localhost
FRONTEND_URL=https://localhost:3000
PROXY_PORT=8080
PORT=8080

**Comment by esteves67** [comment]
> somebody faces some problem?
> please help.
> 
> ![error](https://user-images.githubusercontent.com/70043720/109786377-ac463c00-7c3f-11eb-941e-ab0e3d7e5120.jpg)

How is the frontend and backend ip declared on your's .env? It seems like you are declaring just ` localhost` instead of the machine ip (e.g. 192.168.105.1), otherwise you'll get errors. 
You need to declare the machine ip not just `localhost`, do an `ifconfig` on your frontend/backend machine then declare it in the FRONTEND_URL and BACKEND_URL.
