### ISSUE TITLE
[Bug] Few fixes..

### ISSUE THREAD

**Issue by deepesh-agarwal** [canove/whaticket#5]
A few fixes are needed:

A). Clicking Accept produces Error 500
![Screenshot at Aug 26 08-31-46](https://user-images.githubusercontent.com/3198004/91250520-dbeb2780-e776-11ea-9ae7-70d436e65110.png)

B). Dialogs should use English as Default option.
![Screenshot at Aug 26 08-32-03](https://user-images.githubusercontent.com/3198004/91250591-09d06c00-e777-11ea-807d-b1658f79d3de.png)

**Comment by canove** [comment]
Hi @deepesh-agarwal. 

1 >   I couldn't reproduce it here. It may be related to missing whatsapp session, since when you opens a ticket, Whaticket tries to send a "message seen" to whatsapp number. In your tests, you used de "Demo" account or another one? Can you try it again, after forcing a refresh in your browser? Anyway, it should be better addressed and I'll take a look.

2 > Just updated translations, now every message should be displayed in english. 

Thanks for reporting.

**Comment by esteves67** [comment]
> A few fixes are needed:
> 
> A). Clicking Accept produces Error 500
> ![Screenshot at Aug 26 08-31-46](https://user-images.githubusercontent.com/3198004/91250520-dbeb2780-e776-11ea-9ae7-70d436e65110.png)
> 
> B). Dialogs should use English as Default option.
> ![Screenshot at Aug 26 08-32-03](https://user-images.githubusercontent.com/3198004/91250591-09d06c00-e777-11ea-807d-b1658f79d3de.png)

Try cleaning your browser cache and open the frotend again,
or open the frontend in a incognito tab.

Let me knows if it works for you.

**Comment by esteves67** [comment]
@deepesh-agarwal Try cleaning your browser cache and open the frotend again,
or open the frontend in a incognito tab.

Let me knows if it works for you.

**Comment by esteves67** [comment]
@deepesh-agarwal Try cleaning your browser cache and open the frontend url again,
or open the frontend url in a incognito tab.

Let me knows if it works for you.

**Comment by deepesh-agarwal** [comment]
I was trying this on your demo so yes this was "missing whatsapp session" issue.
