### ISSUE TITLE
How to install on a web server specifically (hostiger)

### ISSUE THREAD

**Issue by rayvicent** [canove/whaticket#57]
Hello @canove interesting project, I would like to install it on the server (hostiger) where my website is located, how would the installation process be? Please if you could give me further indications. try to install it on localhost (local PC) and the Docker installation says it has trouble starting. I did not know how to continue.

**Comment by canove** [comment]
Hi, @rayvicent. How are u doing? 

Sorry, but I don't have any experience with Hostinger. 
About your local environment, could you give more information about it (OS, node version, docker version, etc).

I'll keep this issue open, maybe someone else may help you.

**Comment by ronna** [comment]
Hi, @rayvicent 

Is your hosting account with hostiger a shared hosting service or virtual private server? If its a virtual private server you can follow in the install instructions [https://github.com/canove/whaticket#basic-production-deployment-ubuntu-1804-vps] If its a shared hosting account I am afraid you might not be able to install there since you do not have root access and access to the terminal.

On the local PC is docker running in general? What specific error message did you get. If you do get a trace please post here?
