### ISSUE TITLE
Error creating user. Check the reported data.

### ISSUE THREAD

**Issue by deepesh-agarwal** [canove/whaticket#8]
Followed the instructions but getting this error:

![sshot-1](https://user-images.githubusercontent.com/3198004/91629595-ebbd7280-e9e7-11ea-8bff-7a49619d9021.png)

This is installed on my VPS (without domain setup) and I am accessing this via IP. Where to check error log?

**Comment by canove** [comment]
You can check response data on chrome console (F12), on network tab: 
![image](https://user-images.githubusercontent.com/24817866/91641922-bcb1fb80-e9fd-11ea-9bcd-090ec1c3a4b8.png)

I'm assuming you are running it without Nginx reverse proxy, since you are not using domain names. 
In this case, your .env file should be something like:
`REACT_APP_BACKEND_URL = http://your_vps_ip:8080/`

**Comment by canove** [comment]
Just edited some functions to return a better error. Now the frontend toast should show the real backend error when it occurs.
