### ISSUE TITLE
How to connect to DialogFlow from WA-Web.js



### ISSUE THREAD

**Issue by omdelcastillo** [canove/whaticket#96]
It's possible?
I need to use dialogflow and WA-WEB.js. Please if you give me any clues?

**Comment by esteves67** [comment]
@omdelcastillo 
Since Whaticket uses wa-web.js, you can use all wa-web.js functions, you just need to put the codes (msg.reply or whatever you want) in the `wbotMessageListener.ts` file, that is located at `whaticket/backend/src/services/WbotServices`. 
The file `wbotMessageListener.ts` is the same as the `example.js` file in wa-web.js. Is where it listens for messages and replies messages.

**Comment by esteves67** [comment]
@omdelcastillo 
Since Whaticket uses wa-web.js, you can use all wa-web.js functions, you just need to put the codes (msg.reply or whatever you want) in the `wbotMessageListener.ts` file, that is located at `whaticket/backend/src/services/WbotServices`. 
The file `wbotMessageListener.ts` is the same as the `example.js` file in wa-web.js. Is where it listens for messages and replies messages.
For dialog-flow i haven't used it, but if wa-web.js supports it, Whaticket support it too.
